### ISSUE TITLE
Bot needs modernizing. It doesn't work with newer versions of node / npm

### ISSUE THREAD

**Issue by dmarcos** [supermedium/a-frobot#2]
CC @vincentfretin

**Comment by vincentfretin** [comment]
Do you have any clue of what is not working? Did you see any error or it's just silently not working when creating the dist?
Can you tell me what version of node you tested and how you installed it on the machine.

I'll set up forks of all the repositories and test that on an ubuntu 22.04 server.

**Comment by vincentfretin** [comment]
I always install node with https://github.com/nodesource/distributions/blob/master/README.md#debian-and-ubuntu-based-distributions 
What's your aws instance OS and version?
I never used [nvm](https://github.com/nvm-sh/nvm) to install a version of node, but you probably still need to use that if your instance OS is too old.

**Comment by dmarcos** [comment]
This is how the bot works (from README):

```
npm install -g forever
npm run start
forever logs 0
```

forever we used only works on old versions of node (using node 8.XX on the server atm). And old versions of node fail to generate the builds.

We need to make the bot work with newer versions of node

**Comment by vincentfretin** [comment]
Replace forever by pm2 first
See https://github.com/networked-aframe/networked-aframe/issues/244#issuecomment-1987294846 for instructions.

**Comment by vincentfretin** [comment]
I see [forever](https://github.com/foreversd/forever) is used in different scripts commands, those would need to be replace by the equivalent commands with [pm2](https://github.com/Unitech/pm2)

**Comment by dmarcos** [comment]
@vincentfretin if you can open a quick PR it will be appreciated. thanks

**Comment by vincentfretin** [comment]
I'll look into that in two weeks when I come back from vacation.

**Comment by vincentfretin** [comment]
@dmarcos take a look at #3 
the instructions in the README were misleading, it installed forever globally, but actually the npm start command used the really really old version defined in package.json that was in local node_modules. When you execute a command in npm script, the binary from node_modules/.bin/ take precedence.
